/*
  Each new term in the Fibonacci sequence is generated by adding the previous
  two terms. By starting with 1 and 2, the first 10 terms will be:
  
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  
  By considering the terms in the Fibonacci sequence whose values do not exceed
  four million, find the sum of the even-valued terms. 
*/

function* fibonacci(nth=1) {
  // Generator that yields every nth fibonacci number
  let [next_fib, fib] = [1, 0];
  while (true) {
    yield fib;
    for (let i = 0; i < nth; i++) {
      [next_fib, fib] = [next_fib + fib, next_fib];
    }
  }
}

function PE_002(limit) {
  // Finds the sum of all even fibonacci values below the limit
  // Every third fibonacci number is even
  let fibonacciEven = fibonacci(3)
  let total = 0
  for (let fib of fibonacciEven) {
    if (fib > limit) {
      break;
    } 
    total += fib
  }
  return total
}

let startTime = performance.now();
console.log(PE_002(4 * 10**300))
let endTime = performance.now();
console.log('It took ' + (endTime - startTime) + ' ms.');


